[package]
name = "euler110"
version = "0.1.0"
edition = "2024"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(feature, values("tracing"))'] }

[dependencies]
code-timing-macros = "0.0.6"
num-bigint = "0.4.6"
num-traits = "0.2.19"
